"""empty message

Revision ID: d157dee869e8
Revises: 
Create Date: 2023-04-27 16:03:13.196463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd157dee869e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yatch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('yacht_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=800), nullable=False),
    sa.Column('capacity', sa.String(length=100), nullable=False),
    sa.Column('price', sa.String(length=100), nullable=False),
    sa.Column('yacht_image', sa.String(length=100), nullable=False),
    sa.Column('sailing', sa.Integer(), nullable=False),
    sa.Column('anchorage', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chauffeur_driven_airport',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('car_type', sa.Enum('Chauffeur_Driven_Airport'), nullable=False),
    sa.Column('car_style', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('availability_count', sa.Integer(), nullable=False),
    sa.Column('forPrime', sa.Enum('yes', 'no'), nullable=False),
    sa.Column('agent', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.Column('launch', sa.String(length=100), nullable=False),
    sa.Column('deposit', sa.Integer(), nullable=False),
    sa.Column('driver_allowance', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('toll_fee', sa.Integer(), nullable=False),
    sa.Column('parking_fee', sa.Integer(), nullable=False),
    sa.Column('gst_price', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Inactive'), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car_fleet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id')
    )
    op.create_table('chauffeur_driven_outstation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('car_type', sa.Enum('Chauffeur_Driven_OutStation'), nullable=False),
    sa.Column('car_style', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('availability_count', sa.Integer(), nullable=False),
    sa.Column('forPrime', sa.Enum('yes', 'no'), nullable=False),
    sa.Column('agent', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.Column('launch', sa.String(length=100), nullable=False),
    sa.Column('deposit', sa.Integer(), nullable=False),
    sa.Column('driver_allowance', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('package_hours', sa.Integer(), nullable=False),
    sa.Column('extra_kms', sa.Integer(), nullable=False),
    sa.Column('gst_price', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Inactive'), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car_fleet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id')
    )
    op.create_table('chauffeur_driven_standard',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('car_type', sa.Enum('Chauffeur_Driven_Standard'), nullable=False),
    sa.Column('car_style', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('forPrime', sa.Enum('yes', 'no'), nullable=False),
    sa.Column('availability_count', sa.Integer(), nullable=False),
    sa.Column('agent', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.Column('launch', sa.String(length=100), nullable=False),
    sa.Column('deposit', sa.Integer(), nullable=False),
    sa.Column('driver_allowance', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('package_hours', sa.Integer(), nullable=False),
    sa.Column('extra_kms', sa.Integer(), nullable=False),
    sa.Column('gst_price', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Inactive'), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car_fleet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id')
    )
    op.create_table('self_drive',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('car_type', sa.Enum('Self_Drive'), nullable=False),
    sa.Column('car_style', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('for_prime', sa.Enum('yes', 'no'), nullable=False),
    sa.Column('availability_count', sa.Integer(), nullable=False),
    sa.Column('agent', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.Column('launch', sa.String(length=100), nullable=False),
    sa.Column('deposit', sa.Integer(), nullable=False),
    sa.Column('driver_allowance', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Inactive'), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car_fleet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('self_drive')
    op.drop_table('chauffeur_driven_standard')
    op.drop_table('chauffeur_driven_outstation')
    op.drop_table('chauffeur_driven_airport')
    op.drop_table('yatch')
    # ### end Alembic commands ###
